### ISSUE TITLE
Issue, Smite optimizer wrong paths

### ISSUE THREAD

**Issue by Ivargithub** [MeteorTheLizard/SMITE-Optimizer#10]
Hello, I wanted to use smite optimizer by advice from a friend.

I play smite via steam.
I had a first bug when the path for the backup file was not recognized. It was error 003 and I modified the path which was C:/users /jules/Documents/MyGames/Smite
to C: \ Program Files (x86) \ Steam \ steamapps \ common \ SMITE \ Backups \
because I know smite game via steam was in there. 

Now I have error 004 and looking at the other paths on smite optimizer I see that my engine settings, system settings and game settings are still located in C:/users/jules/Documents/MyGames/Smite while I know it is an error and that they are in the same place as for the backup.
I don't know if I can change these paths manually or if the error really came from there.

Thank you for your help and for readin
![error](https://user-images.githubusercontent.com/97029151/147927135-25d9c945-4384-4ecd-80b2-2659add9e345.PNG)
![Capture](https://user-images.githubusercontent.com/97029151/147927173-68a696ef-2d4f-47d6-9c08-16c49f960b0d.PNG)

**Comment by MeteorTheLizard** [comment]
The backup path is the path to where the program saves your old configuration files to in case you need to restore them. The path should NOT be in the SMITE folder. I recommend using the default path for that.

If that path does not exist and the program returns a 003 error, make sure the program can create folders. Disable your anti-virus program OR try to launch the smite optimizer as administrator.

To fix this problem:
Go into the "Restore Configuration" tab and change the backup path to: C:\Users\ ~ USERNAME ~ \Documents\My Games\SMITE\Backups\

**Comment by Ivargithub** [comment]
Thank you very much for your fast answer.

It worked by launching in administrator+changing the path.
