### ISSUE TITLE
Error: Array

### ISSUE THREAD

**Issue by BesNaej** [MeteorTheLizard/SMITE-Optimizer#11]
When i click ''Apply Changes'' this error message appears
![ERROR](https://user-images.githubusercontent.com/114117601/191628800-d93c3c12-f886-486c-8422-96df125a2a4e.PNG)

**Comment by MeteorTheLizard** [comment]
Have you launched SMITE at least once on your system before?

Also please create a 'debug dump' and upload it here. In the debug tab of the SMITE Optimizer there is a text button in the bottom left that you can create one with.

**Comment by MeteorTheLizard** [comment]
Fixed in v1.3.5
