### ISSUE TITLE
enemy size and health bar bug

### ISSUE THREAD

**Issue by TaberiusRex** [MeteorTheLizard/SMITE-Optimizer#13]
downloaded this yesterday for the first time and while it worked as intended and gave me a great performance boost it somehow bugged enemy's size and health bar size to be much smaller then normal. No idea what triggered it as I have already restored to default, verified and repaired but the bug still persists. [https://imgur.com/a/jCr0yGK](url) image for reference in training mode

**Comment by MeteorTheLizard** [comment]
The configuration files do not get removed when uninstalling the game, meaning they are persistent. Restoring to default settings in the SMITE Optimizer does not affect health bar scaling. The health bar scaling setting should be left untouched by the optimizer unless the configuration files were corrupted before applying in which case the SMITE Optimizer fixes said corruptions before making changes to the file.

You can change the health bar scaling in-game in the user interface tab.

If that doesn't work, you can navigate to your configuration files which should be located in:
C:\Users\ (USERNAME) \Documents\My Games\SMITE\BattleGame\Config
Delete all files inside of that folder (this will reset ALL settings back to default) and then launch the game again. The game will re-create the files and with that fix any issues there might be with them. You can apply the SMITE Optimizer again afterwards.

**Comment by TaberiusRex** [comment]
forgot to mention the health bar scaling along with combat text were set to maximum while still being bugged and tiny, they couldn't be set any higher and were obviously smaller then normal. I just tried deleting the config folder but the bug was still there even tho I could tell from loading in the config had been reset in other ways(audio, music and effects set back to default). Unless there's another folder I should try clearing I guess my best bet would be to just reinstall and hope to avoid any corruption?

**Comment by MeteorTheLizard** [comment]
The health bar scale can also be changed through the HUD Editor. Give that a try.

Since you have fully reset your configuration files, I can safely assume that the issue was not caused by the SMITE Optimizer since it only changes the files that you have just deleted.

You can also try messing around with the resolution, window type, resolution scale.. I'm pretty sure there is an overall HUD scale as well, maybe that's the problem.

I can only make guesses here unfortunately.

**Comment by TaberiusRex** [comment]
changing screen type to borderless window managed to fix it, I messed with all the other settings to no effect. I reapplied the optimizer and seems like it's running smoothly now but I will put it to the ranked game final test first, thanks for helping promptly :)
