### ISSUE TITLE
The program cant find my Smite

### ISSUE THREAD

**Issue by Nandinhah05** [MeteorTheLizard/SMITE-Optimizer#4]
Hi, since the new update, everytime I click to steam game launcher to find my game it says that it couldnt find my smite, i tried to do it manually but it doenst find the launcher neither, I am sure I downloaded the game through the steam and now i cant use the program, thanks! 
![optmizer](https://user-images.githubusercontent.com/71559563/93670265-8b62a380-fa70-11ea-9c88-66c60d5026ed.png)

**Comment by MeteorTheLizard** [comment]
Hello. It appears the recent SMITE patch has changed the names for the configuration files which causes issues. An update will roll out today that fixes this issue.

**Comment by MeteorTheLizard** [comment]
After further investigation it seems to be an issue related to you. Make sure to verify the game files and to launch the game at least once before using the SMITE Optimizer. If the program still says that it cannot find the configuration files try to navigate there manually.

They should be located here:
<Path to your steam installation/library>/steamapps/common/SMITE/BattleGame/Config/

**Comment by Nandinhah05** [comment]
Hi!It didnt work, also i cant find any launcher through these files.

Enviado do Outlook<http://aka.ms/weboutlook>[cid:1f9a3e30-0248-40ca-9af6-e37e563a2f96]
________________________________
De: Meteor <notifications@github.com>
Enviado: sábado, 19 de setembro de 2020 13:15
Para: MeteorTheLizard/SMITE-Optimizer <SMITE-Optimizer@noreply.github.com>
Cc: Nandinhah05 <lazerfernanda@outlook.com>; Author <author@noreply.github.com>
Assunto: Re: [MeteorTheLizard/SMITE-Optimizer] The program cant find my Smite (#4)


After further investigation it seems to be an issue related to you. Make sure to verify the game files and to launch the game at least once before using the SMITE Optimizer. If the program still says that it cannot find the configuration files try to navigate there manually.

They should be located here:
<Path to your steam installation/library>/steamapps/common/SMITE/BattleGame/Config/

**Comment by Nandinhah05** [comment]
It is important to say that the program worked normally before the lastest version, since I update it yesterday it couldnt find my files.

Enviado do Outlook<http://aka.ms/weboutlook>
________________________________
De: Fer A <lazerfernanda@outlook.com>
Enviado: domingo, 20 de setembro de 2020 09:01
Para: MeteorTheLizard/SMITE-Optimizer <reply@reply.github.com>
Assunto: RE: [MeteorTheLizard/SMITE-Optimizer] The program cant find my Smite (#4)

Hi!It didnt work, also i cant find any launcher through these files.

Enviado do Outlook<http://aka.ms/weboutlook>[cid:1f9a3e30-0248-40ca-9af6-e37e563a2f96]
________________________________
De: Meteor <notifications@github.com>
Enviado: sábado, 19 de setembro de 2020 13:15
Para: MeteorTheLizard/SMITE-Optimizer <SMITE-Optimizer@noreply.github.com>
Cc: Nandinhah05 <lazerfernanda@outlook.com>; Author <author@noreply.github.com>
Assunto: Re: [MeteorTheLizard/SMITE-Optimizer] The program cant find my Smite (#4)


After further investigation it seems to be an issue related to you. Make sure to verify the game files and to launch the game at least once before using the SMITE Optimizer. If the program still says that it cannot find the configuration files try to navigate there manually.

They should be located here:
<Path to your steam installation/library>/steamapps/common/SMITE/BattleGame/Config/
