### ISSUE TITLE
Game Crash & Question 

### ISSUE THREAD

**Issue by Samuemue** [MeteorTheLizard/SMITE-Optimizer#7]
Hello, I am currently experiencing a game crash with Smite after I've optimized the settings using Smite Optimizer using the Steam Game Launcher. Basically, while its loading up the Smite Game, it crashes. I'm guessing this is all due to the new Season 8 Update? Or is it something on my end?

I'd like to just say, you deserve more recognition for your work. I found out about Smite Optimizer because there was a Youtube Channel called Rexsi who made a video doing a challenge called the "N64 Challenge" about a year ago and his game graphics were literally N64. Which is what I'm trying to achieve because I love those type of graphics. 

If you need any additional information about the crash, please let me know and I will try my best to assist you.

**Comment by MeteorTheLizard** [comment]
Hello, thank you for your feedback! I really appreciate it. I had no idea that Rexsi made a video about this so thank you for bringing this to my attention, It was hilarious haha. Too bad he didn't link it anywhere considering how many people ask about it.

As for your crashing issue, I was unable to re-create it using the "Lowest possible" settings. For further debugging, I require following files from you:

- A Screenshot of the "Debug" tab in the SMITE Optimizer.
- Launch.log ( Which should be located here: C:\Users\ <USERNAME> \Documents\My Games\Smite\BattleGame\Logs\ )
If it is not located there then your steam version of SMITE does not create or write to it. (At least I'm unaware of any other path)
- Unreal Engine Auto Reporter crash log. When your game crashes the auto reporter should come up and allow you to save the crash log.

You can simply attach these files with your next response. Thank you.

**Comment by Samuemue** [comment]
![debug](https://user-images.githubusercontent.com/80444593/110839693-d87e4000-8271-11eb-9f15-dbb4ba5bd99c.PNG)

[AutoReportLog.txt](https://github.com/MeteorTheLizard/SMITE-Optimizer/files/6125375/AutoReportLog.txt)

[Launch-backup-2021.03.11-14.02.59.log](https://github.com/MeteorTheLizard/SMITE-Optimizer/files/6125425/Launch-backup-2021.03.11-14.02.59.log)

Is the Launch-backup the file you were asking for in your 2nd bullet point?

**Comment by MeteorTheLizard** [comment]
Both log files indicate that the 64 bit version of SMITE is missing on your system. I recommend validating the game files through steam. https://support.steampowered.com/kb_article.php?ref=2037-QEUH-3335

I'm unsure if the error messages after that are valid but apparently some system files are corrupt as well.
To fix any issues with your system files open up an elevated command prompt. (open cmd.exe as admin) and run the following command: **sfc /scannow** Once it is finished it will let you know whether or not there were corrupted files. If there were corrupted files, run the **DISM.exe /Online /Cleanup-image /Restorehealth** command. This will automatically resolve any issues with your system files. It will download any corrupt/missing files from the internet. https://support.microsoft.com/en-us/topic/use-the-system-file-checker-tool-to-repair-missing-or-corrupted-system-files-79aa86cb-ca52-166a-92a3-966e85d4094e

Let me know if this fixes your crashing issue.

**Comment by Samuemue** [comment]
No it did not fix the issue. I did run the **sfc /scannow** command and no corrupt files were found. 

As for Steam, when the "Verify integrity of game files..." completed, it showed this message 

![validation fail on 2 files](https://user-images.githubusercontent.com/80444593/110854608-35cebd00-8283-11eb-839b-eff629f6befe.PNG)

Then it fixes the crash issue but it returns to my previous Settings. 

Oddly enough, I can somewhat achieve what I'm trying to do by going in the BattleSystemSetting
 located in Documents\My Games\Smite\BattleGame\Config\ and everything works fine. Only managed to make the game look the playdough but still having a bit of FPS issues, averaging like 70 FPS max.

**Comment by MeteorTheLizard** [comment]
So verifying the game files worked. That's great news! The program should work perfectly fine now. As for your FPS, there is only so much the program can do. I'd say 70 FPS is pretty good for a laptop with integrated graphics.

You can go into the "Advanced" mode in the SMITE Optimizer and mess with the settings. Hovering over a setting will reveal an explanation of what it does exactly. Maybe you're able to squeeze a bit more FPS out of it this way.

**Comment by Samuemue** [comment]
Yeah, I'll just have to manually edit the settings in the files. Using the Smite Optimizer easily guides me since the Setting names of each option is basically the same or similar to the one in the files. 

Thank you for your help! I'm really surprised people don't know this even exists. Or in general, being able to edit your game graphics this deep.
