### ISSUE TITLE
game crashes and doesnt even open.

### ISSUE THREAD

**Issue by Thecks** [MeteorTheLizard/SMITE-Optimizer#8]
I want to use this on my low end pc and make the graphics a lot lower but every time i do it crashes the game before it opens, on the other hand my brothers pc which is a lot better than mine runs the has no issues with crashes. Is there any way i can fix this?

**Comment by MeteorTheLizard** [comment]
I require the following data from you:

* A Screenshot of the "Debug" tab in the SMITE Optimizer.
* Launch.log ( Which should be located here: C:\Users\ ~ USERNAME ~ \Documents\My Games\Smite\BattleGame\Logs\ )
If it is not located there then your steam version of SMITE does not create or write to it. (At least I'm unaware of any other path)
* Unreal Engine Auto Reporter crash log. When your game crashes the auto reporter should come up and allow you to save the crash log.

You can simply attach these files with your next response. Thank you.

**Comment by MeteorTheLizard** [comment]
According to the backup path, the Launch.log should be stored here:

C:\Users\jerma\OneDrive\Documents\My Games\Smite\BattleGame\Logs\

**Comment by Thecks** [comment]
![Screenshot (6)](https://user-images.githubusercontent.com/85803398/121787981-937ee800-cb97-11eb-990e-61f112f80889.png)
![Screenshot (7)](https://user-images.githubusercontent.com/85803398/121788021-e789cc80-cb97-11eb-9006-0df4fbbca247.png)

**Comment by MeteorTheLizard** [comment]
Same issue as https://github.com/MeteorTheLizard/SMITE-Optimizer/issues/7

The log indicates that the 64 bit version of SMITE is missing on your system. I recommend validating the game files through steam. https://support.steampowered.com/kb_article.php?ref=2037-QEUH-3335

This should fix your crashing issue.

**Comment by Thecks** [comment]
Yes, although it fixes the crash issue I still am not able to use the optimizer to improve my frames. Once I validate the files and try to use the optimizer, the game starts to crash again.

**Comment by MeteorTheLizard** [comment]
The error should be different now. Send me the Launch.log again.

**Comment by Thecks** [comment]
![Screenshot (9)](https://user-images.githubusercontent.com/85803398/121790123-2d4f9080-cbaa-11eb-8903-5223de2359f8.png)
![Screenshot (10)](https://user-images.githubusercontent.com/85803398/121790124-2fb1ea80-cbaa-11eb-8361-b5c930dcfab0.png)
![Screenshot (11)](https://user-images.githubusercontent.com/85803398/121790126-317bae00-cbaa-11eb-90c3-edc677f6a875.png)
![Screenshot (12)](https://user-images.githubusercontent.com/85803398/121790138-5d972f00-cbaa-11eb-9fec-6985616cca38.png)

same issues unfortunately. do you happen to have discord so i can share my screen to you?

**Comment by MeteorTheLizard** [comment]
You can try to launch the game in 32Bit mode. When launching the game via steam, it should ask you whether you want it to start in 32Bit or 64Bit mode. 

If that doesn't work then you can try the following steps in this exact order:

1: Verify game files.
2: Launch the game normally.
3: Close the game.
4: Go to the "Debug" tab in the SMITE Optimizer and reset the configuration paths.
5: Select "Legacy"

If the Legacy mode does not work, click on "More Options" and then "Manual Search", navigate to:
**C:\Users\jerma\OneDrive\Documents\My Games\Smite\BattleGame\Config\**

6: Select: BattleEngine.ini
7: Select: BattleSystemSettings.ini

Apply the optimizer settings again and launch the game normally.

**Comment by Thecks** [comment]
sorry how do i choose battleengine and battlesystemsettings . it doesnt let me hover over both of them and they arent close together.

**Comment by Thecks** [comment]
YOU DID IT thankyou so much!

**Comment by MeteorTheLizard** [comment]
No problem!

Reference stuff that you can ignore:

Version 1.3.1.4

ERROR: Missing closing parenthesis: (bAllowAmbientOcclusion=False
> Import fails due to a malformed variable.

Line:
[Engine.SeqAct_Interp]
RenderingOverrides=(bAllowAmbientOcclusion=False,bAllowDominantWholeSceneDynamicShadows=False,bAllowMotionBlurSkinning=False,bAllowTemporalAA=True,bAllowLightShafts=True)

The parenthesis it refers to is not actually missing. Perhaps this is not used anymore.

The variable restore for "RenderingOverrides" will be removed from the configuration hive so it will simply never exist to potentially fix the crashing issue.
> New Version: 1.3.1.5
