### ISSUE TITLE
crash

### ISSUE THREAD

**Issue by Thecks** [MeteorTheLizard/SMITE-Optimizer#9]
![Screenshot (3)](https://user-images.githubusercontent.com/85803398/121786827-6a0e8e00-cb90-11eb-8e82-e7adbc138858.png)
![Screenshot (5)](https://user-images.githubusercontent.com/85803398/121786838-785caa00-cb90-11eb-81e3-1268e367cc3b.png)

When i go to  C:\Users\ ~ USERNAME ~ \Documents the documents page is empty with no files in it.

**Comment by MeteorTheLizard** [comment]
Duplicate. https://github.com/MeteorTheLizard/SMITE-Optimizer/issues/8

Do not open new issues in order to respond.
